[package]
name = "dioscuri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "6.0.0"
native-tls = "0.2.14"
url = "2.5.4"
x509-parser = "0.17.0"
